name: pdpower
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandapower>=3.2
  - numpy<2
  - pandas<2.3
  - scipy<1.14
  - scikit-learn
  - matplotlib
  - networkx
  - numba
  - pillow
  - pytorch
  - jupyter
  - ipykernel
  - nbconvert
